# Generated by Django 5.0.6 on 2024-11-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerprofile', '0002_remove_customerprofile_factors'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketing',
            name='target_audiences',
        ),
        migrations.AddField(
            model_name='marketing',
            name='target_audiences',
            field=models.ManyToManyField(blank=True, null=True, related_name='marketing', to='customerprofile.customerprofile'),
        ),
    ]
