# Generated by Django 5.0.6 on 2024-11-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerprofile', '0002_remove_customerprofile_factors'),
        ('marketing', '0002_remove_marketing_target_audiences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='target_audiences',
            field=models.ManyToManyField(blank=True, related_name='marketing', to='customerprofile.customerprofile'),
        ),
    ]
