# Generated by Django 5.0.6 on 2024-11-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_marketing_target_audiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='task_end_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marketing',
            name='task_start_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
