# Generated by Django 5.0.6 on 2024-12-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_marketing_task_end_id_marketing_task_start_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='status',
            field=models.CharField(choices=[('undone', 'Undone'), ('working', 'Working'), ('done', 'Done')], default='undone', max_length=10),
        ),
    ]
