# Generated by Django 5.0.6 on 2025-01-09 08:58

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_marketing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='target_rank',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('BR', 'Bronze'), ('SI', 'Silver'), ('GO', 'Gold')], help_text='Select the target ranks for this campaign.', max_length=8),
        ),
    ]
