# Generated by Django 5.0.6 on 2024-11-05 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerprofile', '0001_initial'),
        ('factors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factors',
            old_name='conttract_date',
            new_name='contract_date',
        ),
        migrations.AlterField(
            model_name='factors',
            name='costumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factor', to='customerprofile.customerprofile'),
        ),
    ]
