# Generated by Django 5.0.6 on 2024-12-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0002_rename_conttract_date_factors_contract_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factors',
            name='files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
