# Generated by Django 5.0.6 on 2025-01-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0003_factors_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factors',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factors',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='factors_files/'),
        ),
    ]
