# Generated by Django 5.0.6 on 2024-10-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.BigIntegerField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('national_id', models.BigIntegerField(blank=True, null=True)),
                ('instagram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_rank', models.CharField(blank=True, choices=[('BR', 'Bronze'), ('SI', 'Silver'), ('GO', 'Gold')], max_length=2, null=True)),
                ('factors', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_picture', models.ImageField(blank=True, null=True, upload_to='customer_profile_pictures/')),
            ],
        ),
    ]
