# Generated by Django 5.0.6 on 2024-12-30 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerprofile', '0002_remove_customerprofile_factors'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
