# Generated by Django 5.0.6 on 2025-01-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerprofile', '0003_customerprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='full_name',
            field=models.CharField(max_length=255, unique=False),
        ),
    ]
