# Generated by Django 5.0.6 on 2025-01-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerprofile', '0003_customerprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='buyer_rank',
            field=models.CharField(blank=True, choices=[('BR', 'Bronze'), ('SI', 'Silver'), ('GO', 'Gold')], default='BR', max_length=2),
        ),
    ]
