# Generated by Django 5.0.6 on 2025-01-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerprofile', '0004_alter_customerprofile_buyer_rank'),
        ('customerprofile', '0004_alter_customerprofile_full_name'),
        ('customerprofile', '0004_alter_customerprofile_phone_number'),
    ]

    operations = [
    ]
