# Generated by Django 5.0.6 on 2024-12-23 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_alter_product_product_image_and_more'),
        ('salesopportunities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesopportunity',
            name='selected_products',
        ),
        migrations.CreateModel(
            name='SalesOpportunityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sales_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='salesopportunities.salesopportunity')),
            ],
        ),
    ]
