# Generated by Django 5.0.6 on 2025-01-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesopportunities', '0002_remove_salesopportunity_selected_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesopportunity',
            name='buyer_type',
            field=models.CharField(blank=True, choices=[('OM', 'Omde'), ('KH', 'Khorde')], max_length=2, null=True),
        ),
    ]
