# Generated by Django 5.0.6 on 2025-01-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesopportunities', '0003_salesopportunity_buyer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesopportunity',
            name='sms_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
