# Generated by Django 5.0.6 on 2024-11-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='send_time',
            field=models.TimeField(),
        ),
    ]
