# Generated by Django 5.0.6 on 2024-11-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='send_date',
            field=models.DateField(),
        ),
    ]
