# Generated by Django 5.0.6 on 2024-10-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountemployee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='work_position',
            field=models.CharField(choices=[('admin', 'مدیر کل مجموعه'), ('system_manager', 'مدیر سامانه'), ('accountant', 'حسابدار'), ('regular', 'عادی')], default='regular', max_length=20),
            preserve_default=False,
        ),
    ]
