# Generated by Django 5.0.6 on 2024-10-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountemployee', '0003_alter_customuser_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
