# Generated by Django 5.0.6 on 2024-10-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountemployee', '0006_passwordresetcode_delete_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_assignment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
