# Generated by Django 5.0.6 on 2024-10-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField()),
                ('size', models.CharField()),
                ('color', models.CharField()),
                ('product_image', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
    ]
